# Generated by Django 5.2.9 on 2025-12-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(),
        ),
    ]
